schema_version = "1.0.0"
id = "auto_kerning"
name = "Auto Kerning"
version = "0.0.1"
tagline = "Apply font kerning to a text object's body"
maintainer = "Natasha Brown <natasha@bookflyers.com>"
type = "add-on"
tags = ["Object"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Bookflyers Ltd"]
website = "https://github.com/bookflyers/auto-kerning"

wheels = [
    "./wheels/fonttools-4.61.1-cp311-cp311-macosx_10_9_universal2.whl",
    "./wheels/fonttools-4.61.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/fonttools-4.61.1-cp311-cp311-win_amd64.whl",
    "./wheels/fonttools-4.61.1-py3-none-any.whl",
]

[permissions]
files = "Read font files"

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  "images/",
  ".*",
  "*.blend",
  "*.md",
  "*.zip",
]